### ISSUE TITLE
Diseño de métodos de Setup de la librería

### ISSUE THREAD

**Issue by aaramirez** [synergyvision/fbcache#2]
- [x] Diseñar los métodos de configuración, creación de la instancia, especificación de la configuración.
- [x] Método de creación de la instancia
- [x] Método para especificar la configuración del Cache
- [x] Diseño inicial del archivo de configuración que considere la lista de rutas a las cuales se le realiza cache tanto para Realtime Database como Firestore. Cada ruta tiene una política de refrescamiento en tiempo que puede especificarse en segundos, minutos, horas, días, semanas y meses.
- [x] Agregar un atributo a cada ruta en el archivo de configuración que indique si la ruta es de sólo lectura (r - read only) o de lectura y escritura (rw - read and write).

**Comment by LuisRFuentes54** [comment]
Para el diseño inicial del archivo de configuración de la librería, propongo que el archivo json tenga una estructura como esta
```
[
    {
        "url-firebase": "https://proyecto_en_donde_este_nuestra_bd.firebaseio.com/",
        "credential": "C:\Users\User\dev\firebase\credentials.json",
        "dbms": "rtdb",     
        "collections": [
            {
                "name": "users",
                "refresh": "2 min"
            },
            {
                "name": "photos",
                "refresh": "3 h"
            }
        ]
    }
]
```
Esta estructura le permitiría a la librería poder establecer conexiones a distintos proyectos de Firebase de forma sencilla, ya que como vemos, el objeto de configuración estaría dentro de un arreglo, por lo que, si al leer dicho archivo, la librería comprueba que hay más de 1 objeto en dicho arreglo, puede iniciar la conexión a ambos proyectos sin ningún problema (esta parte sería pensando más en un caso que se necesite conectar a varios proyectos de Firebase en el mismo servidor).

Ya hablando de la estructura que tiene un objeto perteneciente al arreglo principal, tendríamos la URL con la que podemos hacer referencia al proyecto de Firebase en el atributo _url-firebase_, y la ruta donde se almacene el archivo JSON con las credenciales de acceso a dicho proyecto en el atributo _credential_.

El atributo _dbms_ especifica cual es el gestor de base de datos donde se almacenan los datos a los que se quiere hacer caché, se le puede asignar "rtbd" para Real Time Database o "firestore" para Firestore. 

El atributo _collections_ es un arreglo que contiene a que partes exactamente se les quiere hacer el caché, si en el atributo _dbms_ especificamos que queremos usar una caché para Real Time Database, los objetos dentro del atributo _collections_ contendrán el nombre del child al que se le quiere hacer caché (_name_) y el tiempo de refrescamiento de este (_refresh_); esto funciona igual si se especifica que se quiere hacer la caché para Firestore, con la diferencia que el atributo _name_ de los objetos de _collections_ hará referencia al nombre de una collección de Firestore.
(**Nota**: El nombre _collections_ fue escogido porque se puede adaptar tanto para Real Time Database como para Firestore, sin embargo, no es un nombre definitivo aún, también se esta manejando la posibilidad de tener un atributo _childs_ que se usado para Real Time Database, y que _collections_ se usado unicamente si se usa Firestore)

Vemos también que este diseño nos da la posibilidad de asignar distintos tiempos de refrescamiento a cada parte que se vaya a guardar en caché, en un principio se piensa que la forma de indicar el tiempo de refrescamiento sea a través de un string que tenga la siguiente forma "X Y", donde X es la cantidad y Y la unidad de tiempo (ejemplo: Si quiere asignar un refrescamiento cada 30 segundos, en el atributo _refresh_ debería poner "30 s"). Pudiendo usar _s_ para segundos, _min_ para minutos, _h_ para horas, _d_ para días y _m_ para meses.

Por estas razones veo que este diseño puede ser acertado para el archivo de configuración; también se quiere agregar un atributo que permita asignar desde este archivo un máximo de memoria que pueda utilizar la librería, solo que aún se está considerando si ponerlo en cada objeto del atributo _collections_, general para un proyecto, o general para toda la librería. 

Cualquier cosa, este sigue siendo un diseño inicial del archivo, según lo que vaya viendo más las impresiones que tenga este diseño, se podrá mejorar esta propuesta.

**Comment by LuisRFuentes54** [comment]
# Modificación del diseño del archivo de configuración

Esta modificación tiene como objetivo complementar la base de la estructura expuesta en el comentario anterior, buscando es arreglar algunos detalles que se pudieron pasar por alto al momento de hacer el comentario anterior.

En un principio, la estructura del archivo con los cambios propuestos sería la siguiente

```
{
    "connections": [
        {
            "url-firebase": "https://proyecto_en_donde_este_nuestra_bd.firebaseio.com/",
            "credential": "C:\Users\User\dev\firebase\credentials.json",
            "read-only": true,    
            "collections": [
                {
                    "name": "users",
                    "refresh": "2 m"
                },
                {
                    "name": "photos",
                    "refresh": "3 h"
                }
            ],
            "childs": [
                {
                    "name": "persons",
                    "refresh": "4 d"
                }
            ]
        }
    ],
    "max-size": "50 b"
}
```

El primero de los cambios es que lo que se vio en el comentario anterior, ahora esta condensado en un atributo de un objeto, el cual es llamado _connections_, esto porque se agregaron los atributos llamados _max-size_ y _read-only_. 

El atributo _max-size_ determinará cual es la máxima cantidad de memoria caché que puede usar la librería, tiene un formato parecido al del atributo _refresh_, que es de la forma "X Y", donde X es la cantidad e Y es la unidad (ejemplo, si quieres que lo máximo que consuma la librería sea 20 kilobytes, debes poner "20 kb"), donde Y puede ser _b_ para bytes, _kb_ para kilobytes y _mb_ para megabytes.

El atributo _read-only_, tendrá un booleano que indique si la ruta en la que se encuentra esta habilitada para que se puedan hacer operaciones de inserción, actualización y eliminación, o sea únicamente de consulta. Si _read-only_ esta en "true", significa que la ruta solo puede consultarse; en cambio, si esta en "false", se puede hacer consultas a los childs y colecciones de la ruta. _read-only_ será un atributo **opcional**, por lo que se puede indicar una ruta sin necesidad de indicar el valor de este, ya que la librería cuando vea que no se asigno este valor, esta lo entenderá como si se hubiera asignado el valor "false" a _read-only_.

Además, ahora también se va a hacer un cambio con el atributo _dbms_, el cual ahora deja de formar parte del diseño y se agrega el atributo _childs_; este cambio se hace porque después de realizado el diseño inicial, me di cuenta que en un mismo objeto de conexión, no había forma de hacer que en un mismo proyecto se usarían tanto Real Time Database como Firestore, así que se prefirió optar por dejar el atributo _collections_ únicamente para las colecciones de Firestore a las que se les vaya a realizar un caché, y _childs_ para los childs de Real Time Database. Se elimina el atributo _dbms_ ya que ahora se puede saber si se va a usar cualquiera de los manejadores de base de datos de Firebase viendo si los atributos _collections_ y _childs_ tienen rutas indicadas; dejando sin mayor utilidad al atributo _dbms_.

Por ahora, estos son todos los cambios implementados hasta ahora, cualquier nuevo cambio se informará por acá

**Comment by LuisRFuentes54** [comment]
Antes de usar la librería en algún servidor, se debe llamar al método de inicialización para que la librería lea el archivo de configuración, cree lo necesario para las conexiones de los proyectos de Firebase, y alistar la configuración de la caché.

La librería utilizará internamente otras librerías de Node que nos ayudarán a implementar el funcionamiento de esta librería, en el método de inicialización, se harán las configuraciones necesarias para usar estas librerías e implementarlas. Las librerías a usar serán las siguientes:

- firebase-admin: Para establecer conexión a los distintos proyectos de Firebase y realizar las distintas operaciones CRUD con las distintas base de datos que estén en un proyecto (independientemente de si es Real Time Database o Firestore).
- node-cache: Nos permite manejar la caché de una forma sencilla y fácil de implementar.
- moment.js: Nos facilita el manejo de fechas e intervalos de tiempo, cosa que ayudará en gran medida a la hora de establecer intervalos de actualización de lo almacenado en la caché.

**Nota**: En caso de que en un futuro se decida agregar otra librería, se actualizará este comentario

Ahora, se piensa que se llame al método de inicialización de la siguiente forma:

```
const FBCache = require('fb-cache');

FBCache.init( params )
```
Y para los parámetros del método se piensa que se le pase lo siguiente:

- Objeto con las configuraciones que se quieran asignar a la librería para ese proyecto (es decir, el objeto que se tenga en el archivo de configuración)
- *String que contenga la ruta al proyecto al que se quiera realizar almacenamiento en caché (en un futuro se quiere que también se pueda pasar un Array de strings con distintas rutas para que se puedan referenciar varios proyectos)
- *String que contenga la ruta al archivo de credenciales de Firebase o el token OAuth para acceder al proyecto indicado (puede ser opcional si se quiere conectar a una aplicación con la credencial predeterminada de la aplicación de Google)
- *String que contenga el tipo de autenticación de la credencial, indicando si es un archivo de credenciales o un token OAuth (si se quiere conectar con los permisos predeterminados de la aplicación de Google, no es necesario que se pase este parámetro)

*: Por seguridad, se recomienda que estos parámetros se guarden en variables de entorno en la aplicación que se use la librería, y se referencie a esa variable en ves de escribir directamente dicho valor en el código fuente 

Se usan los métodos de autenticación que nos brinda firebase-admin para conectarnos a un proyecto en Firebase, si quiere saber más al respecto, visite este [link](https://firebase.google.com/docs/admin/setup/)

Con estos datos, se quiere que el método de inicialización realice:
- La conexión al proyecto de Firebase
- Establezca la configuración de lo que se vaya a guardar en la memoria caché

Una vez que se ejecute este método, la librería podrá utilizarse en el resto del proyecto
