### ISSUE TITLE
Métodos de consulta

### ISSUE THREAD

**Issue by aaramirez** [synergyvision/fbcache#3]
- [x] Diseñar el método de consulta de una ruta independientemente si es Realtime Database o Firestore.

**Comment by LuisRFuentes54** [comment]
Tomando en cuenta la estructura inicial del archivo de configuración, se tiene que el método para consultar una ruta, independientemente sea hacía Real Time Database o Firestore sería el siguiente:

## Parámetros:
- Nombre de la colección (en caso de estar consultando a Firestore) o child (en caso de estar consultado a Real Time Database)
- Objeto con las condiciones que se quieran aplicar a la consulta (este atributo es opcional, si no se especifica, el método entiende que se quiere obtener todo lo que tenga el child o la colección indicada en el parámetro anterior)

## Flujo:
1. Verifica que el child o la colección indicada se haya especificado en el archivo de configuración
   - En caso de que no esté indicado en el archivo de configuración, se realizará una consulta directa a Firestore o Real Time Database, se retorna la información que cumpla con las condiciones dadas (si se indican condiciones), y finaliza la ejecución del método
2. Verifica lo almacenado en caché
   - En caso de que la información almacenada en memoria tenga que actualizarse, se realizará una consulta directa a Firestore o Real Time Database, con esta información se actualiza lo que se tenga almacenado en caché, se retorna la información que cumpla con las condiciones dadas, y finaliza la ejecución del método
3. Con la información de la caché, se aplican las condiciones dadas, se retorna la información que cumpla con las condiciones dadas y se finaliza la ejecución del método

**Comment by LuisRFuentes54** [comment]
Se va a agregar un parámetro en el método de consulta que permita saber explícitamente si se quiere realizar una consulta sobre Real Time Database o Firestore, entonces, la lista de parámetros queda de la siguiente forma

## Parámetros:
- Nombre del manejador de base de datos que se quiera consultar
- Nombre de la colección (en caso de estar consultando a Firestore) o child (en caso de estar consultado a Real Time Database)
- Objeto con las condiciones que se quieran aplicar a la consulta (este atributo es opcional, si no se especifica, el método entiende que se quiere obtener todo lo que tenga el child o la colección indicada en el parámetro anterior)

El flujo seguiría la misma lógica, con el único cambio que en esa verificación ahora también se tomaría en cuenta el manejador de base de datos que se haya indicado
