### ISSUE TITLE
Métodos de escritura

### ISSUE THREAD

**Issue by aaramirez** [synergyvision/fbcache#4]
- [x] Diseñar los métodos de escritura considerando que hay rutas que están incluidas en el cache y otras no, tanto para Realtime Database o Firestore.

**Comment by LuisRFuentes54** [comment]
El diseño que propongo para los métodos de inserción, modificación y eliminación son los siguientes

## Inserción

### Parámetros:
- Nombre de la colección (en caso de estar insertando a Firestore) o child (en caso de estar insertando a Real Time Database)
- Objeto que se quiera incluir en la colección o child indicado

### Flujo:
1. Comprobar si a la ruta a donde se quiera hacer la inserción no sea de solo lectura
   - En caso de que sea de solo lectura, el método finaliza su ejecución
2. Realiza la petición a Real Time Database o Firestore (según sea el caso) para insertar el objeto obtenido por parámetros al child o colección indicada
3. Verifica que el child o la colección en donde se realizó la inserción esté en el archivo de configuración
   - En caso de que no, el método finaliza su ejecución
4. Actualiza la información en caché, agregando al objeto a los datos que se tengan almacenados en caché

## Actualización

### Parámetros 
- Nombre de la colección (en caso de estar insertando a Firestore) o child (en caso de estar insertando a Real Time Database)
- Objeto con los valores que se quieran asignar
- Condiciones que permitan saber a que registros asignarle los cambios y a cuales no (Este atributo será opcional, si no se asigna, se aplican los cambios a todos los objetos de la colección o child que se indique)

### Flujo:
1. Comprobar si a la ruta a donde se quiera hacer la actualización no sea de solo lectura
   - En caso de que sea de solo lectura, el método finaliza su ejecución
2. Realiza la petición a Real Time Database o Firestore (según sea el caso) para actualizar los registros que cumplan con la condición dada con la información que se pasa por parámetros
3. Verifica que el child o la colección en donde se realizó la actualización esté en el archivo de configuración
   - En caso de que no, el método finaliza su ejecución
4. Actualiza la información en caché, tomando en cuenta las condiciones pasadas por parametros

## Eliminación

### Parámetros 
- Nombre de la colección (en caso de estar insertando a Firestore) o child (en caso de estar insertando a Real Time Database)
- Condiciones que permitan saber que registros eliminar y cuales no (Este atributo será opcional, si no se asigna, se eliminarían todos los registros del child o colección)

### Flujo:
1. Comprobar si a la ruta a donde se quiera hacer la eliminación no sea de solo lectura
   - En caso de que sea de solo lectura, el método finaliza su ejecución
2. Realiza la petición a Real Time Database o Firestore (según sea el caso) para eliminar los registros que cumplan con la condición dada con la información que se pasa por parámetros
3. Verifica que el child o la colección en donde se realizó la actualización esté en el archivo de configuración
   - En caso de que no, el método finaliza su ejecución
4. Actualiza la información en caché, tomando en cuenta las condiciones pasadas por parámetros

**Comment by LuisRFuentes54** [comment]
Al igual que se hizo en el método de consulta, se va a agregar un parámetro en el método de consulta que permita saber explícitamente si se quiere realizar una operación de escritura sobre Real Time Database o Firestore, haciendo que ahora en cada método que se dijo anteriormente aquí, también reciba el siguiente parámetro:

- Nombre del manejador de base de datos que se quiera consultar

El flujo seguiría la misma lógica, con el único cambio que se tomaría en cuenta el manejador de base de datos que se haya indicado
