### ISSUE TITLE
Archivo de configuración

### ISSUE THREAD

**Issue by aaramirez** [synergyvision/fbcache#5]
- [x] Diseñar el archivo de configuración que considere:

- Especificar las variables de ambiente donde se encuentran las credenciales y rutas de acceso a la base de datos Firebase
- Especificar las rutas de Firestore o Realtime Database que estarán incluidas en la política de cache
- Cada ruta debe especificar el tiempo de vigencia, utilizando un tiempo de inicio y periodicidad (start: 6:00, period: 10m -> 6:10, 6:20, 6:30, 6:40..., 7:10, 7:20...) o una cantidad de tiempo fija (2h, 1d, 1sem, 50seg, 45min).
- El archivo debe considerar la configuración de un consumo de memoria máximo y calcular si la información que se desee se le puede hacer cache sin superar el límite.

**Comment by LuisRFuentes54** [comment]
Siguiendo las ideas del #2 para el diseño del archivo de configuración, considero que el diseño más indicado a implementar para el archivo de configuración en este momento es el siguiente:

```
{
    "url": "URL_AL_PROYECTO_DE_FIREBASE",
    "credential": "RUTA_AL_ARCHIVO_DE_CREDENCIALES_O_TOKEN_DE AUTENTICACION",
    "credential_type": "file",   //Indica si la credencial que se esta pasando es un archivo de credenciales o un token OAuth
    "read_only": true,    //Configuración general de solo lectura de la librería, si no se indica por defecto tendrá como valor "true"
    "firestore": [   //Array donde indicamos las colecciones de firestore a las que se le quiere hacer caché
        {
            "name": "users",
            "period": "2 m"
        },
        {
            "name": "photos",
            "refresh": "3 h",
            "read_only": true //Configuración general de solo lectura de la librería, si no se indica se tomará la configuración general, y si esta última no está indica por defecto tendrá como valor "true"
        }
    ],
    "realtime": [   //Array donde indicamos las colecciones de firestore a las que se le quiere hacer caché
        {
            "name": "persons",
            "start": "03-09-2020 06:00 pm",  // siempre debe tener un formato "YYYY-MM-DD hh:mm:ss a"
            "period": "2 d",
            "read_only": false
        },
        {
            "name": "photos",
            "refresh": "4 d",
            "read_only": true
        }
    ],
    "max_size": "50 b"  //Tamaño máximo que puede ocupar la información en caché
}
```

Cada objetos que forma parte de los arreglos _realtime_ y _firestore_, contiene la información hacía que rutas se quieren hacer caché, en estos objetos están los atributos _name_ (indica el nombre de la colleción o child al que se quiere hacer caché), _read\_only_ (indica si esta ruta será de solo léctura (true) o se le pueden hacer operaciones de escritura (flase), por defecto tendrá el valor true), y los atributos _refresh_ , _period_ y _update_ que nos indicarán la configuración que se le dará al refrescamiento de la memoria caché.

Antes que todo, _refresh_ y _period_ no se pueden definir al mismo tiempo. cada uno define una politica de refrescamiento distinta; con _refresh_ se toma una política más simple con el refrescamiento de la memoria caché, ya que lo que hará es renovar la caché una cantidad fija de tiempo (ejemplo, se tiene un refresh de 3 horas, se guardo la información en caché a la 02:00 pm, la información se vencería a las 05:00 pm, si se hace una consulta a las 5:20 pm, se actualiza la información, y esta información va a estar disponible por 3 horas más, es decir, hasta las 8:20 pm). Con _period_ la política se vuelve un poco más estricta, ya que el refrescamiento de la información dependerá del periodo que se tenga y cuanto tiempo falta para cumplir dicho periodo, y para esto se ayuda del atributo, _start_ que indica cuando comienza dicho periodo (si no se define el atributo _start_, se tome como valor de este la hora actual que se tenga cuando se inicie el servidor que use la librería) (ejemplo, se tiene un refresh de 3 horas y un _start_ de "2020-09-03 02:00:00 pm", si se hace una solicitud a las 02:10 pm de esa fecha, se calcula cuantos segundos faltan para las 05:00 pm, y se toma dicho tiempo para saber cuanto tiempo se tendrá esa información guardada en caché, una vez cumplido dicho periodo, si se vuelve a hacer una actualización de la caché, se ve cual sería el siguiente punto según el intervalo, y se asignan los segundos correspondientes hasta llegar a dicha hora).

Si se quiere subir este archivo de configuración a un repositorio público, recomiendo hacer lo siguiente:

1- Definir el archivo de la siguiente forma:
```
{
    "read_only": true,  
    "firestore": [  
        {
            "name": "users",
            "period": "2 m"
        },
        {
            "name": "photos",
            "refresh": "3 h",
            "read_only": true
        }
    ],
    "realtime": [  
        {
            "name": "persons",
            "start": "03-09-2020 06:00 pm",
            "period": "2 d",
            "read_only": false
        },
        {
            "name": "photos",
            "refresh": "4 d",
            "read_only": true
        }
    ],
    "max_size": "50 b"
}
```
Obviando los atributos más sensibles del archivo de configuración

2- Implementar un código parecido al siguiente en donde se vaya a inicializar la librería:
```
import { FBCache } from "fb-cache";
import * as fbConfig from "fbcache.config.json";

fbConfig.url = process.env.FIREBASE_URL;
fbConfig.credential = process.env.CREDENTIAL;
fbConfig.credential_type = process.env.CREDENTIAL_TYPE;

FBCache.init(fbConfig)
```

Hay mejoras que se quieren implementar para luego, por ejemplo, el poder tener varias conexiones a distintos proyectos de Firebase, o la posibilidad de obviar los fines de semanas en la política de refrescamiento, pero prefiero implementar estas funcionalidades más adelante para facilitar el desarrollo de la librería.
